<a href="https://colab.research.google.com/github/Ayushman2005-cmyk/24CSEAIML003/blob/main/Expt_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)

[5 6]


In [17]:

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([8, 9, 10, 11, 12, 13, 14])

add = arr1 + arr2
sub = arr2 - arr1
mul = arr1 * arr2

print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)

Addition [ 9 11 13 15 17 19 21]
Subtraction [7 7 7 7 7 7 7]
Multiplication [ 8 18 30 44 60 78 98]


In [18]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print("Indexing:")
print("Element at index 0:", arr[0])
print("Element at index 3:", arr[3])
print("Last element:", arr[-1])

print("Slicing:")
print("Elements from index 1 to 4:", arr[1:5])
print("First three elements:", arr[:3])
print("Elements from index 2 onwards:", arr[2:])
print("Alternate elements:", arr[::2])

Indexing:
Element at index 0: 1
Element at index 3: 4
Last element: 7
Slicing:
Elements from index 1 to 4: [2 3 4 5]
First three elements: [1 2 3]
Elements from index 2 onwards: [3 4 5 6 7]
Alternate elements: [1 3 5 7]


In [23]:

import numpy as np

A = np.array([[1, 2],[3, 4]])

B = np.array([[5, 6],[7, 8]])

result = np.dot(A, B)

print(result)


[[19 22]
 [43 50]]


In [25]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

minimum = np.min(arr)
maximum = np.max(arr)

average = np.mean(arr)

print("Minimum value:", minimum)
print("Maximum value:", maximum)

avg_min = np.mean(minimum)
avg_max = np.mean(maximum)

print("Average Minimum:", avg_min)
print("Average Maximum:", avg_max)

Minimum value: 1
Maximum value: 6
Average Minimum: 1.0
Average Maximum: 6.0


In [46]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

conc = np.concatenate((A, B))

print("Concatenated Array:", conc)

stack = np.vstack((A, B))

print("Stacking:\n", stack)

Concatenated Array: [1 2 3 4 5 6]
Stacking:
 [[1 2 3]
 [4 5 6]]


In [29]:
import numpy as np

A = np.array([10, 20, 30, 40])
B = np.array([15, 20, 25, 40])

print("A > B :", A > B)
print("A < B :", A < B)
print("A == B :", A == B)
print("A != B :", A != B)
print("A >= B :", A >= B)
print("A <= B :", A <= B)

A > B : [False False  True False]
A < B : [ True False False False]
A == B : [False  True False  True]
A != B : [ True False  True False]
A >= B : [False  True  True  True]
A <= B : [ True  True False  True]


In [49]:
try:
  raw_x = input("Enter x value separated by space:")
  raw_y = input("Enter y value separated by space:")

  x = [float(i) for i in raw_x.split()]
  y = [float(i) for i in raw_y.split()]

  n = len(x)

  if n != len(y):
    print("Error: The values of x and y must be the same")
  elif n<2:
    print("Error: You need to least two point to form a line")
  else:
    sum_x=sum(x)
    sum_y=sum(y)
    sum_xy=sum([x[i]*y[i] for i in range(n)])
    sum_x_sq=sum(x[i]**2 for i in range(n))
    numerator_m = (n*sum_xy)-(sum_x*sum_y)
    denominator_m = (n*sum_x_sq)-(sum_x**2)
    if denominator_m == 0:
      print("Error: Vertical line detected(denominator is zero)")
    else:
      m = numerator_m/denominator_m
      c = sum_y/n-m*(sum_x/n)
      print("Slope (m):",m)
      print("\n"+"-"*30)
      print(f"Slope(m):(m:df)")
      print(f"Intercept(c):(c:df)")
      print(f"Equation: y = (m:df)x(c:df)")
      print("-"*30)
except:
  print("Error: Please enter only number separated by spaces")

Error: Please enter only number separated by spaces


In [50]:
import numpy as np
from scipy import stats
try:
  raw_x=input("Enter X value separated by space: ")
  raw_y=input("Enter Y value separated by space: ")
  x=np.array([float(i) for i in raw_x.split()])
  y=np.array([float(i) for i in raw_y.split()])

  slope, intercept, _, _, _ = stats.linregress(x, y)
  print("\n" + "-"*30)
  print(f"Slope(m):     {slope:.df}")
  print(f"Intercept(c): {intercept:.df}")
  printf(f"Equation:     y = {slope:.df}x + {intercept:.df}")
  print("-" * 30)
except ValueError:
  print("Error: Please enter only numbers separated by space")
except Exception as e:
  print(f"An error occured: {e}")

Enter X value separated by space: 1 2 3 4 5
Enter Y value separated by space: 6 7 8 9 10

------------------------------
Error: Please enter only numbers separated by space
