<a href="https://colab.research.google.com/github/Ayushman2005-cmyk/24CSEAIML003/blob/main/Expt%20-%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)

[5 6]


In [17]:

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([8, 9, 10, 11, 12, 13, 14])

add = arr1 + arr2
sub = arr2 - arr1
mul = arr1 * arr2

print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)

Addition [ 9 11 13 15 17 19 21]
Subtraction [7 7 7 7 7 7 7]
Multiplication [ 8 18 30 44 60 78 98]


In [18]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print("Indexing:")
print("Element at index 0:", arr[0])
print("Element at index 3:", arr[3])
print("Last element:", arr[-1])

print("Slicing:")
print("Elements from index 1 to 4:", arr[1:5])
print("First three elements:", arr[:3])
print("Elements from index 2 onwards:", arr[2:])
print("Alternate elements:", arr[::2])

Indexing:
Element at index 0: 1
Element at index 3: 4
Last element: 7
Slicing:
Elements from index 1 to 4: [2 3 4 5]
First three elements: [1 2 3]
Elements from index 2 onwards: [3 4 5 6 7]
Alternate elements: [1 3 5 7]


In [23]:
#WAP
import numpy as np

A = np.array([[1, 2],[3, 4]])

B = np.array([[5, 6],[7, 8]])

result = np.dot(A, B)

print(result)


[[19 22]
 [43 50]]


In [25]:
#WAP to
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

minimum = np.min(arr)
maximum = np.max(arr)

average = np.mean(arr)

print("Minimum value:", minimum)
print("Maximum value:", maximum)

avg_min = np.mean(minimum)
avg_max = np.mean(maximum)

print("Average Minimum:", avg_min)
print("Average Maximum:", avg_max)

Minimum value: 1
Maximum value: 6
Average Minimum: 1.0
Average Maximum: 6.0


In [46]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

conc = np.concatenate((A, B))

print("Concatenated Array:", conc)

stack = np.vstack((A, B))

print("Stacking:\n", stack)

Concatenated Array: [1 2 3 4 5 6]
Stacking:
 [[1 2 3]
 [4 5 6]]


In [29]:
import numpy as np

A = np.array([10, 20, 30, 40])
B = np.array([15, 20, 25, 40])

print("A > B :", A > B)
print("A < B :", A < B)
print("A == B :", A == B)
print("A != B :", A != B)
print("A >= B :", A >= B)
print("A <= B :", A <= B)

A > B : [False False  True False]
A < B : [ True False False False]
A == B : [False  True False  True]
A != B : [ True False  True False]
A >= B : [False  True  True  True]
A <= B : [ True  True False  True]
